[build]
start = "uvicorn backend.main:app --host 0.0.0.0 --port 8000"

[build.dependencies]
python = "3.11"
uvicorn = "^0.24.0"
fastapi = "^0.104.1"
pydantic = "^2.5.2"

[build.scripts]
build = "pip install -r backend/requirements.txt && npm install && npm run build"
start = "uvicorn backend.main:app --host 0.0.0.0 --port 8000"

[build.ports]
web = 8000

[build.env]
PYTHONPATH = "."

[build.files]
include = ["backend/**", "frontend/**", "requirements.txt"]
